In [31]:
import time
import datetime
import pandas as pd
import yfinance as yf
from yahoo_fin.stock_info import get_data
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [2]:
pip install yahoo_fin

Collecting yahoo_fin
  Downloading yahoo_fin-0.8.9.1-py3-none-any.whl (10 kB)
Collecting feedparser
  Downloading feedparser-6.0.10-py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 2.0 MB/s eta 0:00:011
Collecting requests-html
  Downloading requests_html-0.10.0-py3-none-any.whl (13 kB)
Requirement already satisfied: pandas in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from yahoo_fin) (1.3.4)
Requirement already satisfied: requests in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from yahoo_fin) (2.26.0)
Collecting sgmllib3k
  Downloading sgmllib3k-1.0.0.tar.gz (5.8 kB)
Requirement already satisfied: python-dateutil>=2.7.3 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from pandas->yahoo_fin) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from pandas->yahoo_fin) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from pandas->yahoo_fin) (1.20.3)
Requirement already satisfied: six>=1.5 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from python-dateutil>=2.7.3->pandas->yahoo_fin) (1.16.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from requests->yahoo_fin) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from requests->yahoo_fin) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from requests->yahoo_fin) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from requests->yahoo_fin) (2022.5.18.1)
Collecting parse
  Downloading parse-1.19.0.tar.gz (30 kB)
Collecting fake-useragent
  Downloading fake-useragent-0.1.11.tar.gz (13 kB)
Collecting pyquery
  Downloading pyquery-1.4.3-py3-none-any.whl (22 kB)
Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Collecting pyppeteer>=0.0.14
  Downloading pyppeteer-1.0.2-py3-none-any.whl (83 kB)
     |████████████████████████████████| 83 kB 1.4 MB/s  eta 0:00:01
Collecting w3lib
  Downloading w3lib-1.22.0-py2.py3-none-any.whl (20 kB)
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (1.4.4)
Requirement already satisfied: importlib-metadata>=1.4 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.8.1)
Collecting pyee<9.0.0,>=8.1.0
  Downloading pyee-8.2.2-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (4.62.3)
Requirement already satisfied: websockets<11.0,>=10.0 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from pyppeteer>=0.0.14->requests-html->yahoo_fin) (10.3)
Requirement already satisfied: zipp>=0.5 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html->yahoo_fin) (3.6.0)
Requirement already satisfied: typing-extensions>=3.6.4 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html->yahoo_fin) (3.10.0.2)
Requirement already satisfied: beautifulsoup4 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from bs4->requests-html->yahoo_fin) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from beautifulsoup4->bs4->requests-html->yahoo_fin) (2.2.1)
Collecting cssselect>0.7.9
  Downloading cssselect-1.1.0-py2.py3-none-any.whl (16 kB)
Requirement already satisfied: lxml>=2.1 in /Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages (from pyquery->requests-html->yahoo_fin) (4.6.3)
Building wheels for collected packages: bs4, fake-useragent, parse, sgmllib3k
  Building wheel for bs4 (setup.py) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1271 sha256=af3226ed705323c6b12d64e23f8ef4d3b689d2215d97fb87f30d46846c91482a
  Stored in directory: /Users/robbyodum/Library/Caches/pip/wheels/0a/9e/ba/20e5bbc1afef3a491f0b3bb74d508f99403aabe76eda2167ca
  Building wheel for fake-useragent (setup.py) ... done
  Created wheel for fake-useragent: filename=fake_useragent-0.1.11-py3-none-any.whl size=13502 sha256=bb29c700f2f79a950d4d14be9783220280e9046bb83683dc5f0b5580df2cfff7
  Stored in directory: /Users/robbyodum/Library/Caches/pip/wheels/ed/f7/62/50ab6c9a0b5567267ab76a9daa9d06315704209b2c5d032031
  Building wheel for parse (setup.py) ... done
  Created wheel for parse: filename=parse-1.19.0-py3-none-any.whl size=24591 sha256=4a638d1586f02660bb8449cbf903d05ba0e02611f1d7901524120c92c90ff668
  Stored in directory: /Users/robbyodum/Library/Caches/pip/wheels/9c/aa/cc/f2228050ccb40f22144b073f15a2c84f11204f29fc0dce028e
  Building wheel for sgmllib3k (setup.py) ... done
  Created wheel for sgmllib3k: filename=sgmllib3k-1.0.0-py3-none-any.whl size=6065 sha256=509d9231c3a2328997cb4fb672d1f7a295c55e9ab8fc4171abf522d23a5b1a4e
  Stored in directory: /Users/robbyodum/Library/Caches/pip/wheels/73/ad/a4/0dff4a6ef231fc0dfa12ffbac2a36cebfdddfe059f50e019aa
Successfully built bs4 fake-useragent parse sgmllib3k
Installing collected packages: pyee, cssselect, w3lib, sgmllib3k, pyquery, pyppeteer, parse, fake-useragent, bs4, requests-html, feedparser, yahoo-fin
Successfully installed bs4-0.0.1 cssselect-1.1.0 fake-useragent-0.1.11 feedparser-6.0.10 parse-1.19.0 pyee-8.2.2 pyppeteer-1.0.2 pyquery-1.4.3 requests-html-0.10.0 sgmllib3k-1.0.0 w3lib-1.22.0 yahoo-fin-0.8.9.1
Note: you may need to restart the kernel to use updated packages.

Bitcoin

In [4]:
BTC_df = get_data("BTC-USD", start_date="6/30/2019", end_date="06/30/2022", index_as_date = True, interval="1d")
Dodge_df = get_data("DOGE-USD", start_date="6/30/2019", end_date="06/30/2022", index_as_date = True, interval="1d")
Eth_df = get_data("ETH-USD", start_date="6/30/2019", end_date="06/30/2022", index_as_date = True, interval="1d")
Ada_df = get_data("ADA-USD", start_date="6/30/2019", end_date="06/30/2022", index_as_date = True, interval="1d")
Xrp_df = get_data("XRP-USD", start_date="6/30/2019", end_date="06/30/2022", index_as_date = True, interval="1d")

Top5 = [BTC_df,Dodge_df,Eth_df,Ada_df,Xrp_df]
Total_df = pd.concat(Top5, axis=1)

Total_df.head()

,open,high,low,close,adjclose,volume,ticker,open,high,low,...,adjclose,volume,ticker,open,high,low,close,adjclose,volume,ticker
2019-06-30,11931.991211,12178.383789,10799.008789,10817.155273,10817.155273,27256473494,BTC-USD,0.003418,0.003446,0.003247,...,0.082098,161855807,ADA-USD,0.429180,0.429180,0.396411,0.396411,0.396411,1570726856,XRP-USD
2019-07-01,10796.930664,11206.439453,10089.314453,10583.134766,10583.134766,29378589324,BTC-USD,0.003250,0.003325,0.003093,...,0.083822,168654991,ADA-USD,0.395900,0.417618,0.389673,0.406862,0.406862,1783852226,XRP-USD
2019-07-02,10588.683594,10912.188477,9737.884766,10801.677734,10801.677734,31015895223,BTC-USD,0.003237,0.003360,0.003080,...,0.081077,180980795,ADA-USD,0.406414,0.409737,0.384477,0.400204,0.400204,1676193189,XRP-USD
2019-07-03,10818.156250,11968.078125,10818.156250,11961.269531,11961.269531,30796494294,BTC-USD,0.003207,0.003336,0.003172,...,0.082998,154492407,ADA-USD,0.400178,0.409239,0.396724,0.408532,0.408532,1436716899,XRP-USD
2019-07-04,11972.718750,12006.075195,11166.569336,11215.437500,11215.437500,25920294033,BTC-USD,0.003314,0.003357,0.003131,...,0.077774,142713205,ADA-USD,0.408316,0.408655,0.387974,0.388719,0.388719,1385563454,XRP-USD

In [248]:
btc_df = Total_df.iloc[:,0:6]
btc_df = btc_df.iloc[:,0:4]
btc_df.head()

                    open          high           low         close
2019-06-30  11931.991211  12178.383789  10799.008789  10817.155273
2019-07-01  10796.930664  11206.439453  10089.314453  10583.134766
2019-07-02  10588.683594  10912.188477   9737.884766  10801.677734
2019-07-03  10818.156250  11968.078125  10818.156250  11961.269531
2019-07-04  11972.718750  12006.075195  11166.569336  11215.437500

In [249]:
btc_df = btc_df.iloc[::-1]
btc_df['shifted_close'] = btc_df['close'].shift(-1)
btc_df.dropna(inplace=True)
btc_df.head()

,open,high,low,close,shifted_close
2022-06-30,20108.312500,20141.160156,18729.656250,19784.726562,20104.023438
2022-06-29,20281.169922,20364.156250,19937.791016,20104.023438,20280.634766
2022-06-28,20731.544922,21164.423828,20228.812500,20280.634766,20735.478516
2022-06-27,21028.238281,21478.089844,20620.199219,20735.478516,21027.294922
2022-06-26,21496.494141,21783.724609,21016.269531,21027.294922,21502.337891

In [235]:
btc_df.tail()

,open,high,low,close,shifted_close
2022-01-06,43565.511719,43748.718750,42645.539062,43160.929688,43569.003906
2022-01-05,45899.359375,46929.046875,42798.222656,43569.003906,45897.574219
2022-01-04,46458.851562,47406.546875,45752.464844,45897.574219,46458.117188
2022-01-03,47343.542969,47510.726562,45835.964844,46458.117188,47345.218750
2022-01-02,47680.925781,47881.406250,46856.937500,47345.218750,47686.812500

In [250]:
X = btc_df.iloc[:,0:4]
Y = btc_df['shifted_close']
X.head()

                    open          high           low         close
2022-06-30  20108.312500  20141.160156  18729.656250  19784.726562
2022-06-29  20281.169922  20364.156250  19937.791016  20104.023438
2022-06-28  20731.544922  21164.423828  20228.812500  20280.634766
2022-06-27  21028.238281  21478.089844  20620.199219  20735.478516
2022-06-26  21496.494141  21783.724609  21016.269531  21027.294922

In [84]:
0.7*len(btc_df)

766.5

In [251]:
X_train, X_test, Y_train, Y_test = X.iloc[:767], X.iloc[767:], Y.iloc[:767], Y.iloc[767:] 
X_train.dropna(inplace=True)
X_test.dropna(inplace=True)
Y_train.dropna(inplace=True)
Y_test.dropna(inplace=True)

/Users/robbyodum/opt/anaconda3/envs/dev/lib/python3.7/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

In [189]:
X_train.tail()

                    open          high           low         close
2021-07-31  42196.304688  42231.449219  41110.832031  41626.195312
2021-08-01  41460.843750  42541.679688  39540.941406  39974.894531
2021-08-02  39907.261719  40419.179688  38746.347656  39201.945312
2021-08-03  39178.402344  39750.031250  37782.050781  38152.980469
2021-08-04  38213.332031  39952.296875  37589.164062  39747.503906

In [99]:
X_scalar = StandardScaler()

In [100]:
scaled_data_train = X_scalar.fit_transform(X_train)
scaled_data_test = X_scalar.fit_transform(X_test)

In [101]:
X_scaled_train = X_scalar.transform(X_train)
X_scaled_test = X_scalar.transform(X_test)

In [102]:
X_scaled_train_df = pd.DataFrame(
    X_scaled_train,
    columns=X.columns
)
X_scaled_test_df = pd.DataFrame(
    X_scaled_test,
    columns=X.columns
)
display(X_scaled_train_df.head())
display(X_scaled_test_df.head())

       open      high       low     close  adjclose    volume
0 -3.119686 -3.126480 -3.165592 -3.199841 -3.199841 -0.468356
1 -3.230055 -3.219096 -3.235639 -3.222446 -3.222446 -0.246952
2 -3.250304 -3.247135 -3.270325 -3.201336 -3.201336 -0.076128
3 -3.227991 -3.146520 -3.163702 -3.089327 -3.089327 -0.099019
4 -3.115725 -3.142899 -3.129314 -3.161370 -3.161370 -0.607763

       open      high       low     close  adjclose    volume
0 -0.415296 -0.347501 -0.534351 -0.296968 -0.296968  0.358846
1 -0.306260 -0.163618 -0.290150 -0.108906 -0.108906  0.676167
2 -0.115003 -0.028479 -0.025004  0.059100  0.059100  0.864421
3  0.054348  0.027980  0.045403 -0.014088 -0.014088  0.475451
4 -0.021741  0.139895 -0.002291  0.233896  0.233896  0.729125

In [276]:
neuron = Sequential()

In [277]:
number_input_features = len(X_train.iloc[0])

In [278]:
hidden_nodes = (number_input_features + 1) / 2

In [279]:
number_input_features

4

In [280]:
# neuron.add(Dense(units = hidden_nodes, activation = 'relu',input_dim = number_input_features))
neuron.add(Dense(units = 8, activation = 'relu',input_dim = number_input_features))

In [281]:
# neuron.add(Dense(units = (hidden_nodes + 1) // 2, activation = 'relu'))
neuron.add(Dense(units = 8, activation = 'relu'))

In [282]:
neuron.add(Dense(units = 1, activation='linear'))

In [283]:
neuron.summary()

Model: "sequential_19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_52 (Dense)            (None, 8)                 40

 dense_53 (Dense)            (None, 8)                 72

 dense_54 (Dense)            (None, 1)                 9

=================================================================
Total params: 121
Trainable params: 121
Non-trainable params: 0
_________________________________________________________________

In [284]:
neuron.compile(loss = 'mse',optimizer='adam',metrics=['mse'])

In [285]:
model = neuron.fit(X_train,Y_train,epochs=100)

Epoch 1/100
24/24 [==============================] - 3s 22ms/step - loss: 1033664064.0000 - accuracy: 0.0000e+00
Epoch 2/100
24/24 [==============================] - 0s 18ms/step - loss: 674416128.0000 - accuracy: 0.0000e+00
Epoch 3/100
24/24 [==============================] - 0s 18ms/step - loss: 341681344.0000 - accuracy: 0.0000e+00
Epoch 4/100
24/24 [==============================] - 1s 20ms/step - loss: 110610384.0000 - accuracy: 0.0000e+00
Epoch 5/100
24/24 [==============================] - 0s 17ms/step - loss: 16610187.0000 - accuracy: 0.0000e+00
Epoch 6/100
24/24 [==============================] - 1s 22ms/step - loss: 740946.6250 - accuracy: 0.0000e+00
Epoch 7/100
24/24 [==============================] - 1s 22ms/step - loss: 310225.0000 - accuracy: 0.0000e+00
Epoch 8/100
24/24 [==============================] - 0s 19ms/step - loss: 280082.8438 - accuracy: 0.0000e+00
Epoch 9/100
24/24 [==============================] - 0s 19ms/step - loss: 271748.5000 - accuracy: 0.0000e+00
Epoch 10/100
24/24 [==============================] - 0s 20ms/step - loss: 271622.6875 - accuracy: 0.0000e+00
Epoch 11/100
24/24 [==============================] - 1s 20ms/step - loss: 271963.4062 - accuracy: 0.0000e+00
Epoch 12/100
24/24 [==============================] - 1s 20ms/step - loss: 271183.5625 - accuracy: 0.0000e+00
Epoch 13/100
24/24 [==============================] - 1s 23ms/step - loss: 270759.3125 - accuracy: 0.0000e+00
Epoch 14/100
24/24 [==============================] - 1s 21ms/step - loss: 271024.4062 - accuracy: 0.0000e+00
Epoch 15/100
24/24 [==============================] - 1s 22ms/step - loss: 270741.8750 - accuracy: 0.0000e+00
Epoch 16/100
24/24 [==============================] - 0s 18ms/step - loss: 270648.9688 - accuracy: 0.0000e+00
Epoch 17/100
24/24 [==============================] - 0s 19ms/step - loss: 270159.9062 - accuracy: 0.0000e+00
Epoch 18/100
24/24 [==============================] - 1s 25ms/step - loss: 271040.8438 - accuracy: 0.0000e+00
Epoch 19/100
24/24 [==============================] - 0s 19ms/step - loss: 269738.9375 - accuracy: 0.0000e+00
Epoch 20/100
24/24 [==============================] - 1s 22ms/step - loss: 270071.9688 - accuracy: 0.0000e+00
Epoch 21/100
24/24 [==============================] - 0s 21ms/step - loss: 269596.7188 - accuracy: 0.0000e+00
Epoch 22/100
24/24 [==============================] - 1s 24ms/step - loss: 269559.0000 - accuracy: 0.0000e+00
Epoch 23/100
24/24 [==============================] - 0s 18ms/step - loss: 268905.3125 - accuracy: 0.0000e+00
Epoch 24/100
24/24 [==============================] - 1s 22ms/step - loss: 268779.6562 - accuracy: 0.0000e+00
Epoch 25/100
24/24 [==============================] - 1s 22ms/step - loss: 268974.7812 - accuracy: 0.0000e+00
Epoch 26/100
24/24 [==============================] - 1s 22ms/step - loss: 268052.2188 - accuracy: 0.0000e+00
Epoch 27/100
24/24 [==============================] - 1s 20ms/step - loss: 267887.4375 - accuracy: 0.0000e+00
Epoch 28/100
24/24 [==============================] - 0s 15ms/step - loss: 268839.6562 - accuracy: 0.0000e+00
Epoch 29/100
24/24 [==============================] - 0s 18ms/step - loss: 268793.2500 - accuracy: 0.0000e+00
Epoch 30/100
24/24 [==============================] - 1s 21ms/step - loss: 267731.6562 - accuracy: 0.0000e+00
Epoch 31/100
24/24 [==============================] - 0s 17ms/step - loss: 267813.4375 - accuracy: 0.0000e+00
Epoch 32/100
24/24 [==============================] - 0s 20ms/step - loss: 266534.6875 - accuracy: 0.0000e+00
Epoch 33/100
24/24 [==============================] - 0s 21ms/step - loss: 266560.5625 - accuracy: 0.0000e+00
Epoch 34/100
24/24 [==============================] - 1s 22ms/step - loss: 266043.7812 - accuracy: 0.0000e+00
Epoch 35/100
24/24 [==============================] - 0s 17ms/step - loss: 265823.8750 - accuracy: 0.0000e+00
Epoch 36/100
24/24 [==============================] - 1s 22ms/step - loss: 265384.2188 - accuracy: 0.0000e+00
Epoch 37/100
24/24 [==============================] - 1s 22ms/step - loss: 265462.1875 - accuracy: 0.0000e+00
Epoch 38/100
24/24 [==============================] - 1s 21ms/step - loss: 265493.0000 - accuracy: 0.0000e+00
Epoch 39/100
24/24 [==============================] - 1s 23ms/step - loss: 264526.2500 - accuracy: 0.0000e+00
Epoch 40/100
24/24 [==============================] - 1s 23ms/step - loss: 264308.4062 - accuracy: 0.0000e+00
Epoch 41/100
24/24 [==============================] - 0s 19ms/step - loss: 265155.3438 - accuracy: 0.0000e+00
Epoch 42/100
24/24 [==============================] - 1s 24ms/step - loss: 263566.2500 - accuracy: 0.0000e+00
Epoch 43/100
24/24 [==============================] - 1s 23ms/step - loss: 263476.4375 - accuracy: 0.0000e+00
Epoch 44/100
24/24 [==============================] - 0s 18ms/step - loss: 262690.5938 - accuracy: 0.0000e+00
Epoch 45/100
24/24 [==============================] - 1s 20ms/step - loss: 262449.9688 - accuracy: 0.0000e+00
Epoch 46/100
24/24 [==============================] - 0s 13ms/step - loss: 262602.0625 - accuracy: 0.0000e+00
Epoch 47/100
24/24 [==============================] - 0s 19ms/step - loss: 261745.4375 - accuracy: 0.0000e+00
Epoch 48/100
24/24 [==============================] - 1s 22ms/step - loss: 261424.6250 - accuracy: 0.0000e+00
Epoch 49/100
24/24 [==============================] - 1s 23ms/step - loss: 261573.0000 - accuracy: 0.0000e+00
Epoch 50/100
24/24 [==============================] - 1s 24ms/step - loss: 263125.6875 - accuracy: 0.0000e+00
Epoch 51/100
24/24 [==============================] - 0s 21ms/step - loss: 261953.4844 - accuracy: 0.0000e+00
Epoch 52/100
24/24 [==============================] - 0s 16ms/step - loss: 260194.8438 - accuracy: 0.0000e+00
Epoch 53/100
24/24 [==============================] - 1s 19ms/step - loss: 259650.2500 - accuracy: 0.0000e+00
Epoch 54/100
24/24 [==============================] - 0s 15ms/step - loss: 258651.5625 - accuracy: 0.0000e+00
Epoch 55/100
24/24 [==============================] - 0s 18ms/step - loss: 259071.7969 - accuracy: 0.0000e+00
Epoch 56/100
24/24 [==============================] - 1s 22ms/step - loss: 257725.1406 - accuracy: 0.0000e+00
Epoch 57/100
24/24 [==============================] - 0s 16ms/step - loss: 257657.1406 - accuracy: 0.0000e+00
Epoch 58/100
24/24 [==============================] - 0s 17ms/step - loss: 258097.3906 - accuracy: 0.0000e+00
Epoch 59/100
24/24 [==============================] - 1s 23ms/step - loss: 257489.2969 - accuracy: 0.0000e+00
Epoch 60/100
24/24 [==============================] - 0s 18ms/step - loss: 258652.2812 - accuracy: 0.0000e+00
Epoch 61/100
24/24 [==============================] - 0s 16ms/step - loss: 256731.1250 - accuracy: 0.0000e+00
Epoch 62/100
24/24 [==============================] - 1s 26ms/step - loss: 256001.5625 - accuracy: 0.0000e+00
Epoch 63/100
24/24 [==============================] - 0s 17ms/step - loss: 255219.5938 - accuracy: 0.0000e+00
Epoch 64/100
24/24 [==============================] - 1s 22ms/step - loss: 255593.1562 - accuracy: 0.0000e+00
Epoch 65/100
24/24 [==============================] - 0s 17ms/step - loss: 253260.8750 - accuracy: 0.0000e+00
Epoch 66/100
24/24 [==============================] - 1s 24ms/step - loss: 254015.6875 - accuracy: 0.0000e+00
Epoch 67/100
24/24 [==============================] - 0s 20ms/step - loss: 252870.7656 - accuracy: 0.0000e+00
Epoch 68/100
24/24 [==============================] - 0s 19ms/step - loss: 253050.5625 - accuracy: 0.0000e+00
Epoch 69/100
24/24 [==============================] - 0s 17ms/step - loss: 254440.6719 - accuracy: 0.0000e+00
Epoch 70/100
24/24 [==============================] - 0s 17ms/step - loss: 252214.3906 - accuracy: 0.0000e+00
Epoch 71/100
24/24 [==============================] - 1s 20ms/step - loss: 250720.1406 - accuracy: 0.0000e+00
Epoch 72/100
24/24 [==============================] - 1s 22ms/step - loss: 250240.6719 - accuracy: 0.0000e+00
Epoch 73/100
24/24 [==============================] - 1s 24ms/step - loss: 250148.0000 - accuracy: 0.0000e+00
Epoch 74/100
24/24 [==============================] - 0s 19ms/step - loss: 249492.2344 - accuracy: 0.0000e+00
Epoch 75/100
24/24 [==============================] - 1s 20ms/step - loss: 250032.0000 - accuracy: 0.0000e+00
Epoch 76/100
24/24 [==============================] - 1s 26ms/step - loss: 248791.1406 - accuracy: 0.0000e+00
Epoch 77/100
24/24 [==============================] - 0s 21ms/step - loss: 247534.5625 - accuracy: 0.0000e+00
Epoch 78/100
24/24 [==============================] - 0s 16ms/step - loss: 246974.7969 - accuracy: 0.0000e+00
Epoch 79/100
24/24 [==============================] - 0s 17ms/step - loss: 246539.8281 - accuracy: 0.0000e+00
Epoch 80/100
24/24 [==============================] - 0s 18ms/step - loss: 246688.7656 - accuracy: 0.0000e+00
Epoch 81/100
24/24 [==============================] - 0s 17ms/step - loss: 246522.5156 - accuracy: 0.0000e+00
Epoch 82/100
24/24 [==============================] - 1s 22ms/step - loss: 246671.6875 - accuracy: 0.0000e+00
Epoch 83/100
24/24 [==============================] - 0s 15ms/step - loss: 245004.3125 - accuracy: 0.0000e+00
Epoch 84/100
24/24 [==============================] - 0s 18ms/step - loss: 243897.7812 - accuracy: 0.0000e+00
Epoch 85/100
24/24 [==============================] - 0s 18ms/step - loss: 244148.2188 - accuracy: 0.0000e+00
Epoch 86/100
24/24 [==============================] - 0s 17ms/step - loss: 245201.5156 - accuracy: 0.0000e+00
Epoch 87/100
24/24 [==============================] - 0s 20ms/step - loss: 240132.6562 - accuracy: 0.0000e+00
Epoch 88/100
24/24 [==============================] - 0s 16ms/step - loss: 241394.6719 - accuracy: 0.0000e+00
Epoch 89/100
24/24 [==============================] - 0s 16ms/step - loss: 241026.1094 - accuracy: 0.0000e+00
Epoch 90/100
24/24 [==============================] - 0s 18ms/step - loss: 241378.1875 - accuracy: 0.0000e+00
Epoch 91/100
24/24 [==============================] - 1s 20ms/step - loss: 239841.4844 - accuracy: 0.0000e+00
Epoch 92/100
24/24 [==============================] - 0s 19ms/step - loss: 240897.7656 - accuracy: 0.0000e+00
Epoch 93/100
24/24 [==============================] - 0s 15ms/step - loss: 237532.9062 - accuracy: 0.0000e+00
Epoch 94/100
24/24 [==============================] - 0s 19ms/step - loss: 238513.5781 - accuracy: 0.0000e+00
Epoch 95/100
24/24 [==============================] - 0s 14ms/step - loss: 237558.7344 - accuracy: 0.0000e+00
Epoch 96/100
24/24 [==============================] - 0s 20ms/step - loss: 236669.1406 - accuracy: 0.0000e+00
Epoch 97/100
24/24 [==============================] - 0s 16ms/step - loss: 236259.4375 - accuracy: 0.0000e+00
Epoch 98/100
24/24 [==============================] - 0s 12ms/step - loss: 235090.0469 - accuracy: 0.0000e+00
Epoch 99/100
24/24 [==============================] - 0s 17ms/step - loss: 233799.9062 - accuracy: 0.0000e+00
Epoch 100/100
24/24 [==============================] - 0s 15ms/step - loss: 232666.5781 - accuracy: 0.0000e+00

In [288]:
neuron.evaluate(X_test, Y_test)

11/11 [==============================] - 1s 15ms/step - loss: 11065.4512 - accuracy: 0.0000e+00

[11065.451171875, 0.0]

In [ ]:
# LSTM

In [291]:
11065**.5

105.19030373565806

In [289]:
X_test

                    open          high           low         close
2020-05-24   9212.283203   9288.404297   8787.250977   8790.368164
2020-05-23   9185.062500   9302.501953   9118.108398   9209.287109
2020-05-22   9080.334961   9232.936523   9008.638672   9182.577148
2020-05-21   9522.740234   9555.242188   8869.930664   9081.761719
2020-05-20   9725.329102   9804.793945   9447.201172   9522.981445
...                  ...           ...           ...           ...
2019-07-05  11203.102539  11395.661133  10874.964844  10978.459961
2019-07-04  11972.718750  12006.075195  11166.569336  11215.437500
2019-07-03  10818.156250  11968.078125  10818.156250  11961.269531
2019-07-02  10588.683594  10912.188477   9737.884766  10801.677734
2019-07-01  10796.930664  11206.439453  10089.314453  10583.134766

[329 rows x 4 columns]

In [286]:
model_loss, model_accuracy = neuron.evaluate(X_scaled_test,Y_test,verbose=2)

ValueError: Data cardinality is ambiguous:
  x sizes: 328
  y sizes: 329
Make sure all arrays contain the same number of samples.

In [292]:
predictions = neuron.predict(X_test)
results = pd.DataFrame({'predictions':predictions.ravel(),'actual':Y_test})
results.head()

11/11 [==============================] - 0s 9ms/step

            predictions       actual
2020-05-24  9122.498047  9209.287109
2020-05-23  9209.688477  9182.577148
2020-05-22  9114.228516  9081.761719
2020-05-21  9366.098633  9522.981445
2020-05-20  9681.529297  9729.038086